src/Acme.BookStore.Blazor/Pages/Shared/Components/FontAwesome/FontAwesomeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace Acme.BookStore.Blazor.Pages.Components.FontAwesome
{
    public class FontAwesomeViewComponent : AbpViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("/Pages/Shared/Components/FontAwesome/Default.cshtml");
        }
    }
}

src/Acme.BookStore.Blazor/Pages/Shared/Components/FontAwesome/Default.cshtml
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fortawesome/fontawesome-free@6.1.1/css/all.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fortawesome/fontawesome-free@6.1.1/css/v4-shims.min.css">

src/Acme.BookStore.Blazor/Pages/_Host.cshtml
@page "/"
@namespace Acme.BookStore.Blazor.Pages
@using System.Globalization
@using Volo.Abp.AspNetCore.Components.Server.BasicTheme.Bundling
@using Volo.Abp.AspNetCore.Components.Web.BasicTheme.Themes.Basic
@using Volo.Abp.Localization
@{
    Layout = null;
    var rtl = CultureHelper.IsRtl ? "rtl" : string.Empty;
}

<!DOCTYPE html>
<html lang="@CultureInfo.CurrentCulture.Name" dir="@rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Acme.BookStore.Blazor</title>
    <base href="~/" />

    <abp-style-bundle name="@BlazorBasicThemeBundles.Styles.Global" />
    @await Component.InvokeAsync("FontAwesome")
</head>
<body class="abp-application-layout bg-light @rtl">
    <component type="typeof(App)" render-mode="Server" />

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <abp-script-bundle name="@BlazorBasicThemeBundles.Scripts.Global" />
</body>
</html>